version: '3'
services:
  movie:
    image: vkarkalle/movieservice:v1
    ports:
      - "8000:80"
    deploy:
      replicas: 4

  train:
    image: vkarkalle/busservice:v1
    ports:
      - "8001:80"
     deploy:
      replicas: 4

  recharge:
    image: vkarkalle/rechargeservice:v1
    ports:
      - "8002:80"
     deploy:
      replicas: 4

